models/Image.php
<?php
/**
 * Created by PhpStorm.
 * User: olre
 * Date: 31.08.16
 * Time: 20:49
 */

namespace app\models;

use yii\base\Model;

class Image extends Model
{
    public $image;

    public function rules()
    {
        return [
            [['image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, gif, bmp'],
        ];
    }
}

models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use app\models\Image;
use Imagick;

class SiteController extends Controller
{
    const IMAGE_SESSION_NAME = 'imageName';
    const EXTENSION_SESSION_NAME = 'extension';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'model' => new Image(),
        ]);
    }

    /**
     * Get directory path to user images
     *
     * @return string
     */
    private function getDirectoryPath()
    {
        return Yii::getAlias('@webroot/tmp') . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR;
    }

    /**
     * Get url path to user images
     *
     * @return string
     */
    private function getUrlPath()
    {
        return '/tmp/' . Yii::$app->session->id . '/';
    }

    /**
     * Uploads image
     *
     * @return string
     */
    public function actionUpload()
    {
        Yii::$app->session->open();
        $imageFile = UploadedFile::getInstanceByName('Image[image]');
        $directory = $this->getDirectoryPath();
        if (!is_dir($directory)) {
            FileHelper::createDirectory($directory);
        }

        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $uid . '.' . $imageFile->extension;
            $filePath = $directory . $fileName;

            if ($imageFile->saveAs($filePath)) {
                $url = $this->getUrlPath() . $fileName;
                Yii::$app->session->set(self::IMAGE_SESSION_NAME, $fileName);
                Yii::$app->session->set(self::EXTENSION_SESSION_NAME, $imageFile->extension);

                return Json::encode([
                    'file' => [
                        'name' => $fileName,
                        'size' => $imageFile->size,
                        'url' => $url,
                        'thumbnailUrl' => $url,
                    ]
                ]);
            }
        }

        return '';
    }

    /**
     * Betterize image
     */
    public function actionBetterize()
    {
        if ($fileName = Yii::$app->session->get(self::IMAGE_SESSION_NAME)) {
            $directory = $this->getDirectoryPath();
            $filePath = $directory . $fileName;

            $image = new Imagick($filePath);
            $image->autoLevelImage(Imagick::CHANNEL_ALL);
            $image->contrastImage(true);
            $image->modulateImage(106, 150, 100);

            $uid = uniqid(time(), true);
            $resultFileName = $uid . '_result.' . Yii::$app->session->get(self::EXTENSION_SESSION_NAME);
            $resultFilePath = $directory . $resultFileName;
            if ($image->writeImage($resultFilePath)) {
                $url = $this->getUrlPath() . $resultFileName;
                return Json::encode([
                    'file' => [
                        'url' => $url,
                    ]
                ]);
            }
        }
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Test project',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use dosamigos\fileupload\FileUpload;
use yii\bootstrap\Button;

$this->title = 'Test project';
?>
<div class="site-index">
    <div class="col-md-6 col-xs-12">
        <img id="original" src="" alt="">
        <?= FileUpload::widget([
            'model' => $model,
            'attribute' => 'image',
            'url' => ['site/upload'],
            'options' => [
                'accept' => 'image/*'
            ],
            'clientOptions' => [
                'maxFileSize' => 2000000
            ],
            'clientEvents' => [
                'fileuploaddone' => 'function(e, data) {
                    $(document).trigger("imageUploaded", data);
                }',
            ]
        ]); ?>
    </div>
    <div class="col-md-6 col-xs-12">
        <img id="product" src="" alt="">
        <?= Button::widget([
            'label' => 'Make better',
            'options' => [
                'id' => 'makeBetter',
                'class' => ['btn-primary']
            ]
        ]); ?>
    </div>
</div>